
export const sets: any[] = [
  {
    code: 'DGM',
    name: "Dragon's Maze",
    type: 'expansion',
    booster: [
      ['rare', 'mythic rare'],
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Return to Ravnica',
    onlineOnly: false,
  },
  {
    code: 'DIS',
    name: 'Dissension',
    type: 'expansion',
    booster: [
      'rare',
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Ravnica',
    onlineOnly: false,
  },
  {
    code: 'GPT',
    name: 'Guildpact',
    type: 'expansion',
    booster: [
      'rare',
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Ravnica',
    onlineOnly: false,
  },
  {
    code: 'GRN',
    name: 'Guilds of Ravnica',
    type: 'expansion',
    booster: [
      ['rare', 'mythic rare'],
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
  {
    code: 'GTC',
    name: 'Gatecrash',
    type: 'expansion',
    booster: [
      ['rare', 'mythic rare'],
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Return to Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PDGM',
    name: "Dragon's Maze Promos",
    type: 'promo',
    releaseDate: new Date(),
    block: 'Return to Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PDIS',
    name: 'Dissension Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PGPT',
    name: 'Guildpact Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PGRN',
    name: 'Guilds of Ravnica Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PGTC',
    name: 'Gatecrash Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Return to Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PRAV',
    name: 'Ravnica: City of Guilds Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PRNA',
    name: 'Ravnica Allegiance Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PRTR',
    name: 'Return to Ravnica Promos',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Return to Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PRW2',
    name: 'RNA Ravnica Weekend',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
  {
    code: 'PRWK',
    name: 'GRN Ravnica Weekend',
    type: 'promo',
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
  {
    code: 'RAV',
    name: 'Ravnica: City of Guilds',
    type: 'expansion',
    booster: [
      'rare',
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Ravnica',
    onlineOnly: false,
  },
  {
    code: 'RNA',
    name: 'Ravnica Allegiance',
    type: 'expansion',
    booster: [
      ['rare', 'mythic rare'],
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
  {
    code: 'RTR',
    name: 'Return to Ravnica',
    type: 'expansion',
    booster: [
      ['rare', 'mythic rare'],
      'uncommon',
      'uncommon',
      'uncommon',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Return to Ravnica',
    onlineOnly: false,
  },
  {
    code: 'WAR',
    name: 'War of the Spark',
    type: 'expansion',
    booster: [
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
      'common',
    ],
    releaseDate: new Date(),
    block: 'Guilds of Ravnica',
    onlineOnly: false,
  },
];
